# This was taken by downloading the variables from the URL below
# response = requests.get("https://api.census.gov/data/2020/dec/pl/variables.json")

# variables_df = pd.DataFrame([
#    {**value, **{'variable': key}} for key, value in response.json()['variables'].items()
# ]).set_index('variable')
# variable_race_mapping = variables_df[variables_df.group=='P1'][['label']].to_dict()['label']
# variable_hispanic_mapping = variables_df[variables_df.group=='P2'][['label']].to_dict()['label']

variable_race_mapping = {
    "P1_009N": " !!Total:!!Population of two or more races:",
    "P1_008N": " !!Total:!!Population of one race:!!Some Other Race alone",
    "P1_007N": " !!Total:!!Population of one race:!!Native Hawaiian and Other Pacific Islander alone",
    "P1_019N": " !!Total:!!Population of two or more races:!!Population of two races:!!Black or African American; Some Other Race",
    "P1_018N": " !!Total:!!Population of two or more races:!!Population of two races:!!Black or African American; Native Hawaiian and Other Pacific Islander",
    "P1_006N": " !!Total:!!Population of one race:!!Asian alone",
    "P1_029N": " !!Total:!!Population of two or more races:!!Population of three races:!!White; Black or African American; Native Hawaiian and Other Pacific Islander",
    "P1_005N": " !!Total:!!Population of one race:!!American Indian and Alaska Native alone",
    "P1_017N": " !!Total:!!Population of two or more races:!!Population of two races:!!Black or African American; Asian",
    "P1_016N": " !!Total:!!Population of two or more races:!!Population of two races:!!Black or African American; American Indian and Alaska Native",
    "P1_028N": " !!Total:!!Population of two or more races:!!Population of three races:!!White; Black or African American; Asian",
    "P1_004N": " !!Total:!!Population of one race:!!Black or African American alone",
    "P1_027N": " !!Total:!!Population of two or more races:!!Population of three races:!!White; Black or African American; American Indian and Alaska Native",
    "P1_039N": " !!Total:!!Population of two or more races:!!Population of three races:!!Black or African American; American Indian and Alaska Native; Some Other Race",
    "P1_003N": " !!Total:!!Population of one race:!!White alone",
    "P1_015N": " !!Total:!!Population of two or more races:!!Population of two races:!!White; Some Other Race",
    "P1_054N": " !!Total:!!Population of two or more races:!!Population of four races:!!White; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander",
    "P1_066N": " !!Total:!!Population of two or more races:!!Population of five races:!!White; Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P1_030N": " !!Total:!!Population of two or more races:!!Population of three races:!!White; Black or African American; Some Other Race",
    "P1_042N": " !!Total:!!Population of two or more races:!!Population of three races:!!Black or African American; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P1_040N": " !!Total:!!Population of two or more races:!!Population of three races:!!Black or African American; Asian; Native Hawaiian and Other Pacific Islander",
    "P1_065N": " !!Total:!!Population of two or more races:!!Population of five races:!!White; Black or African American; American Indian and Alaska Native; Asian; Some Other Race",
    "P1_041N": " !!Total:!!Population of two or more races:!!Population of three races:!!Black or African American; Asian; Some Other Race",
    "P1_053N": " !!Total:!!Population of two or more races:!!Population of four races:!!White; Black or African American; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P1_051N": " !!Total:!!Population of two or more races:!!Population of four races:!!White; Black or African American; Asian; Native Hawaiian and Other Pacific Islander",
    "P1_052N": " !!Total:!!Population of two or more races:!!Population of four races:!!White; Black or African American; Asian; Some Other Race",
    "P1_064N": " !!Total:!!Population of two or more races:!!Population of five races:!!White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander",
    "P1_050N": " !!Total:!!Population of two or more races:!!Population of four races:!!White; Black or African American; American Indian and Alaska Native; Some Other Race",
    "P1_062N": " !!Total:!!Population of two or more races:!!Population of four races:!!American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P1_063N": " !!Total:!!Population of two or more races:!!Population of five races:",
    "P1_061N": " !!Total:!!Population of two or more races:!!Population of four races:!!Black or African American; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P1_060N": " !!Total:!!Population of two or more races:!!Population of four races:!!Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P1_071N": " !!Total:!!Population of two or more races:!!Population of six races:!!White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P1_070N": " !!Total:!!Population of two or more races:!!Population of six races:",
    "P1_038N": " !!Total:!!Population of two or more races:!!Population of three races:!!Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander",
    "P1_014N": " !!Total:!!Population of two or more races:!!Population of two races:!!White; Native Hawaiian and Other Pacific Islander",
    "P1_026N": " !!Total:!!Population of two or more races:!!Population of three races:",
    "P1_002N": " !!Total:!!Population of one race:",
    "P1_049N": " !!Total:!!Population of two or more races:!!Population of four races:!!White; Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander",
    "P1_025N": " !!Total:!!Population of two or more races:!!Population of two races:!!Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P1_037N": " !!Total:!!Population of two or more races:!!Population of three races:!!Black or African American; American Indian and Alaska Native; Asian",
    "P1_001N": " !!Total:",
    "P1_013N": " !!Total:!!Population of two or more races:!!Population of two races:!!White; Asian",
    "P1_036N": " !!Total:!!Population of two or more races:!!Population of three races:!!White; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P1_048N": " !!Total:!!Population of two or more races:!!Population of four races:!!White; Black or African American; American Indian and Alaska Native; Asian",
    "P1_012N": " !!Total:!!Population of two or more races:!!Population of two races:!!White; American Indian and Alaska Native",
    "P1_024N": " !!Total:!!Population of two or more races:!!Population of two races:!!Asian; Some Other Race",
    "P1_047N": " !!Total:!!Population of two or more races:!!Population of four races:",
    "P1_059N": " !!Total:!!Population of two or more races:!!Population of four races:!!Black or African American; American Indian and Alaska Native; Asian; Some Other Race",
    "P1_023N": " !!Total:!!Population of two or more races:!!Population of two races:!!Asian; Native Hawaiian and Other Pacific Islander",
    "P1_035N": " !!Total:!!Population of two or more races:!!Population of three races:!!White; Asian; Some Other Race",
    "P1_011N": " !!Total:!!Population of two or more races:!!Population of two races:!!White; Black or African American",
    "P1_058N": " !!Total:!!Population of two or more races:!!Population of four races:!!Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander",
    "P1_034N": " !!Total:!!Population of two or more races:!!Population of three races:!!White; Asian; Native Hawaiian and Other Pacific Islander",
    "P1_046N": " !!Total:!!Population of two or more races:!!Population of three races:!!Asian; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P1_010N": " !!Total:!!Population of two or more races:!!Population of two races:",
    "P1_022N": " !!Total:!!Population of two or more races:!!Population of two races:!!American Indian and Alaska Native; Some Other Race",
    "P1_069N": " !!Total:!!Population of two or more races:!!Population of five races:!!Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P1_045N": " !!Total:!!Population of two or more races:!!Population of three races:!!American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P1_057N": " !!Total:!!Population of two or more races:!!Population of four races:!!White; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P1_021N": " !!Total:!!Population of two or more races:!!Population of two races:!!American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander",
    "P1_033N": " !!Total:!!Population of two or more races:!!Population of three races:!!White; American Indian and Alaska Native; Some Other Race",
    "P1_056N": " !!Total:!!Population of two or more races:!!Population of four races:!!White; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P1_068N": " !!Total:!!Population of two or more races:!!Population of five races:!!White; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P1_032N": " !!Total:!!Population of two or more races:!!Population of three races:!!White; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander",
    "P1_044N": " !!Total:!!Population of two or more races:!!Population of three races:!!American Indian and Alaska Native; Asian; Some Other Race",
    "P1_020N": " !!Total:!!Population of two or more races:!!Population of two races:!!American Indian and Alaska Native; Asian",
    "P1_067N": " !!Total:!!Population of two or more races:!!Population of five races:!!White; Black or African American; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P1_043N": " !!Total:!!Population of two or more races:!!Population of three races:!!American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander",
    "P1_055N": " !!Total:!!Population of two or more races:!!Population of four races:!!White; American Indian and Alaska Native; Asian; Some Other Race",
    "P1_031N": " !!Total:!!Population of two or more races:!!Population of three races:!!White; American Indian and Alaska Native; Asian",
}

variable_hispanic_mapping = {
    "P2_070N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of five races:!!White; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P2_071N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of five races:!!Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P2_073N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of six races:!!White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P2_072N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of six races:",
    "P2_060N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of four races:!!Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander",
    "P2_030N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!White; Black or African American; Asian",
    "P2_054N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of four races:!!White; Black or African American; Asian; Some Other Race",
    "P2_042N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!Black or African American; Asian; Native Hawaiian and Other Pacific Islander",
    "P2_066N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of five races:!!White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander",
    "P2_043N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!Black or African American; Asian; Some Other Race",
    "P2_031N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!White; Black or African American; Native Hawaiian and Other Pacific Islander",
    "P2_067N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of five races:!!White; Black or African American; American Indian and Alaska Native; Asian; Some Other Race",
    "P2_055N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of four races:!!White; Black or African American; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P2_032N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!White; Black or African American; Some Other Race",
    "P2_020N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of two races:!!Black or African American; Native Hawaiian and Other Pacific Islander",
    "P2_056N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of four races:!!White; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander",
    "P2_044N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!Black or African American; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P2_068N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of five races:!!White; Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P2_021N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of two races:!!Black or African American; Some Other Race",
    "P2_045N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander",
    "P2_033N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!White; American Indian and Alaska Native; Asian",
    "P2_069N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of five races:!!White; Black or African American; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P2_057N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of four races:!!White; American Indian and Alaska Native; Asian; Some Other Race",
    "P2_062N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of four races:!!Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P2_061N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of four races:!!Black or African American; American Indian and Alaska Native; Asian; Some Other Race",
    "P2_063N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of four races:!!Black or African American; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P2_051N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of four races:!!White; Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander",
    "P2_050N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of four races:!!White; Black or African American; American Indian and Alaska Native; Asian",
    "P2_052N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of four races:!!White; Black or African American; American Indian and Alaska Native; Some Other Race",
    "P2_040N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander",
    "P2_064N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of four races:!!American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P2_041N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!Black or African American; American Indian and Alaska Native; Some Other Race",
    "P2_065N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of five races:",
    "P2_053N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of four races:!!White; Black or African American; Asian; Native Hawaiian and Other Pacific Islander",
    "P2_038N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!White; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P2_026N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of two races:!!Asian; Some Other Race",
    "P2_014N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of two races:!!White; American Indian and Alaska Native",
    "P2_002N": " !!Total:!!Hispanic or Latino",
    "P2_027N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of two races:!!Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P2_015N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of two races:!!White; Asian",
    "P2_039N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!Black or African American; American Indian and Alaska Native; Asian",
    "P2_003N": " !!Total:!!Not Hispanic or Latino:",
    "P2_016N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of two races:!!White; Native Hawaiian and Other Pacific Islander",
    "P2_004N": " !!Total:!!Not Hispanic or Latino:!!Population of one race:",
    "P2_028N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:",
    "P2_005N": " !!Total:!!Not Hispanic or Latino:!!Population of one race:!!White alone",
    "P2_029N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!White; Black or African American; American Indian and Alaska Native",
    "P2_017N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of two races:!!White; Some Other Race",
    "P2_010N": " !!Total:!!Not Hispanic or Latino:!!Population of one race:!!Some Other Race alone",
    "P2_034N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!White; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander",
    "P2_022N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of two races:!!American Indian and Alaska Native; Asian",
    "P2_058N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of four races:!!White; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P2_046N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!American Indian and Alaska Native; Asian; Some Other Race",
    "P2_059N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of four races:!!White; Asian; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P2_023N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of two races:!!American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander",
    "P2_011N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:",
    "P2_047N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P2_035N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!White; American Indian and Alaska Native; Some Other Race",
    "P2_048N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!Asian; Native Hawaiian and Other Pacific Islander; Some Other Race",
    "P2_012N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of two races:",
    "P2_036N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!White; Asian; Native Hawaiian and Other Pacific Islander",
    "P2_024N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of two races:!!American Indian and Alaska Native; Some Other Race",
    "P2_049N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of four races:",
    "P2_037N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of three races:!!White; Asian; Some Other Race",
    "P2_001N": " !!Total:",
    "P2_025N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of two races:!!Asian; Native Hawaiian and Other Pacific Islander",
    "P2_013N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of two races:!!White; Black or African American",
    "P2_018N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of two races:!!Black or African American; American Indian and Alaska Native",
    "P2_006N": " !!Total:!!Not Hispanic or Latino:!!Population of one race:!!Black or African American alone",
    "P2_007N": " !!Total:!!Not Hispanic or Latino:!!Population of one race:!!American Indian and Alaska Native alone",
    "P2_019N": " !!Total:!!Not Hispanic or Latino:!!Population of two or more races:!!Population of two races:!!Black or African American; Asian",
    "P2_008N": " !!Total:!!Not Hispanic or Latino:!!Population of one race:!!Asian alone",
    "P2_009N": " !!Total:!!Not Hispanic or Latino:!!Population of one race:!!Native Hawaiian and Other Pacific Islander alone",
}
